# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: lachie-tapp 1.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "lachie-tapp".freeze
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Lachie Cox".freeze]
  s.date = "2017-10-16"
  s.description = "tap { pp self }".freeze
  s.email = "lachiec@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/tapp.eg.rb",
    "lachie-tapp.gemspec",
    "lib/tapp.rb",
    "tapp.gemspec"
  ]
  s.homepage = "http://github.com/lachie/tapp".freeze
  s.rubygems_version = "2.6.13".freeze
  s.summary = "tap { pp self } (lachie's verison)".freeze
end

